# Generated by Django 5.0.1 on 2024-01-09 00:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lib", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrow",
            name="loan_date",
        ),
        migrations.AddField(
            model_name="borrow",
            name="borrow_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
