[project]
name = "machine-learning-v2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.0.0",
    "ipympl>=0.9.8",
    "ipywidgets>=8.1.7",
    "kagglehub>=0.3.13",
    "matplotlib>=3.10.7",
    "nbformat>=5.10.4",
    "numpy>=2.3.3",
    "optuna>=4.6.0",
    "optuna-dashboard>=0.20.0",
    "pandas>=2.3.3",
    "plotly>=6.3.1",
    "scikit-learn>=1.7.2",
    "scipy>=1.16.2",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.5",
    "torch>=2.8.0",
    "ucimlrepo>=0.0.7",
]
